apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-lang-app
spec:
  replicas: 1 # Optional: define number of pods
  selector:
    matchLabels:
      app: go-lang-app
  template:
    metadata:
      labels:
        app: go-lang-app
    spec:
      containers:
        - name: go-lang-app
          image: hapy1308/happy:go-lang-app
          ports:
            - containerPort: 8080
